### ISSUE TITLE
Drop `moment` lib

### ISSUE THREAD

**Issue by 413d** [mazhuravlev/vdt-stats#1]
Здравствуйте. Заметил в Вашем довольно прогрессивном проекте использование неактуальной библиотеки `Moment`. Думаю, что вам стоит ее убрать или заменить.

<img width="1611" alt="image" src="https://github.com/mazhuravlev/vdt-stats/assets/20566780/62efd28c-5fc2-4cc8-91f3-47cc6fe52aad">

**Comment by mazhuravlev** [comment]
Заменено на date-fns в https://github.com/mazhuravlev/vdt-stats/commit/e0bbd3dd808851a4ec4dd3c0d38f4f1909fd22c3.
